#!/bin/bash
# Stage 1B: Train segmentation model with semi-supervised learning
#
# Uses real labels (0-199) + pseudo labels (200-999) generated by ensemble voting.
# This is the recommended approach for best segmentation performance.

set -e

DATA_ROOT="./data/train"
PSEUDO_LABELS_DIR="./data/pseudo_labels"
OUTPUT_DIR="./checkpoints/seg_semi"
ENCODER="efficientnet-b4"
IMAGE_SIZE=512
BATCH_SIZE=8
NUM_EPOCHS=100
LR=1e-4

echo "========================================"
echo "Stage 1B: Semi-Supervised Seg Training"
echo "========================================"

python csv_train_seg_semi.py \
    --data_root ${DATA_ROOT} \
    --output_dir ${OUTPUT_DIR} \
    --encoder ${ENCODER} \
    --batch_size ${BATCH_SIZE} \
    --num_epochs ${NUM_EPOCHS} \
    --learning_rate ${LR} \
    --image_size ${IMAGE_SIZE} \
    --view both \
    --seed 42 \
    --use_pseudo_labels \
    --pseudo_labels_dir ${PSEUDO_LABELS_DIR}

echo ""
echo "Semi-supervised seg model saved to: ${OUTPUT_DIR}/best_model.pth"
